AWSTemplateFormatVersion: '2010-09-09'

Description: Workshop Compute

Resources:

  WorkshopEC2Role:
    Type: AWS::IAM::Role

    Properties:

      AssumeRolePolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Effect: Allow

            Principal:
              Service:
                - ec2.amazonaws.com

            Action:
              - sts:AssumeRole

      ManagedPolicyArns:

        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess


  WorkshopInstanceProfile:
    Type: AWS::IAM::InstanceProfile

    Properties:

      Roles:
        - !Ref WorkshopEC2Role


  DemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup

    Properties:

      GroupDescription: Demo Security Group

      VpcId: !ImportValue WorkshopVPC

      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0


  DemoInstance:
    Type: AWS::EC2::Instance

    Properties:

      InstanceType: t3.micro

      # Ubuntu 22.04
      ImageId: ami-0d52744d6551d851e

      SubnetId: !ImportValue WorkshopPublicSubnet1A

      IamInstanceProfile:
        !Ref WorkshopInstanceProfile

      SecurityGroupIds:
        - !Ref DemoSecurityGroup

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          apt update

          apt install openjdk-17-jdk -y

          apt install ruby-full wget -y

          cd /tmp

          wget https://aws-codedeploy-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/latest/install

          chmod +x install

          ./install auto

          systemctl enable codedeploy-agent

          systemctl start codedeploy-agent

          mkdir -p /opt/workshop

          echo "Setup Complete" > /opt/workshop/setup.txt

      Tags:
        - Key: Name
          Value: WorkshopApp


Outputs:

  InstanceId:
    Value: !Ref DemoInstance

  SecurityGroupId:
    Value: !Ref DemoSecurityGroup
