AWSTemplateFormatVersion: '2010-09-09'

Resources:

  DemoSecurityGroup:

    Type: AWS::EC2::SecurityGroup

    Properties:

      GroupDescription: Demo SG

      VpcId: !ImportValue WorkshopVPC

      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  DemoInstance:

    Type: AWS::EC2::Instance

    Properties:

      InstanceType: t3.micro

      ImageId: ami-0d52744d6551d851e

      SubnetId: !ImportValue WorkshopPublicSubnet1A
      SecurityGroupIds:
        - !Ref DemoSecurityGroup

      Tags:
        - Key: Name
          Value: WorkshopApp
