AWSTemplateFormatVersion: '2010-09-09'

Description: Workshop Network

Resources:

  WorkshopVPC:
    Type: AWS::EC2::VPC

    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

      Tags:
        - Key: Name
          Value: WorkshopVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

    Properties:
      Tags:
        - Key: Name
          Value: WorkshopIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment

    Properties:
      VpcId: !Ref WorkshopVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1A:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId: !Ref WorkshopVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: true

      Tags:
        - Key: Name
          Value: PublicSubnet-1A

  PublicSubnet1C:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId: !Ref WorkshopVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: true

      Tags:
        - Key: Name
          Value: PublicSubnet-1C

  
