AWSTemplateFormatVersion: '2010-09-09'

Description: Workshop Network

Resources:

  WorkshopVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

      Tags:
        - Key: Name
          Value: workshop-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref WorkshopVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WorkshopVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: true

      Tags:
        - Key: Name
          Value: PublicSubnet-1A

  PublicSubnet1C:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WorkshopVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: true

      Tags:
        - Key: Name
          Value: PublicSubnet-1C

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WorkshopVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway

    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1AAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1A

  PublicSubnet1CAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1C

Outputs:

  VPCId:
    Description: VPC ID
    Value: !Ref WorkshopVPC
    Export:
      Name: WorkshopVPC

  PublicSubnet1AOutput:
    Description: Public Subnet 1A
    Value: !Ref PublicSubnet1A
    Export:
      Name: WorkshopPublicSubnet1A

  PublicSubnet1COutput:
    Description: Public Subnet 1C
    Value: !Ref PublicSubnet1C
    Export:
      Name: WorkshopPublicSubnet1C
