name: TEST-DEBUG-12345

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Current Directory
        run: |
          echo "===== CURRENT DIRECTORY ====="
          pwd

      - name: Show Files
        run: |
          echo "===== FILES ====="
          find .

      - name: Show Network File
        run: |
          echo "===== NETWORK YAML ====="
          cat cloudformation/network.yaml

      - name: Validate Network
        run: |
          echo "===== VALIDATING NETWORK ====="
          aws cloudformation validate-template \
            --template-body file://cloudformation/network.yaml

      - name: Show Database File
        run: |
          echo "===== DATABASE YAML ====="
          cat cloudformation/database.yaml

      - name: Validate Database
        run: |
          echo "===== VALIDATING DATABASE ====="
          aws cloudformation validate-template \
            --template-body file://cloudformation/database.yaml

      - name: Show Compute File
        run: |
          echo "===== COMPUTE YAML ====="
          cat cloudformation/compute.yaml

      - name: Validate Compute
        run: |
          echo "===== VALIDATING COMPUTE ====="
          aws cloudformation validate-template \
            --template-body file://cloudformation/compute.yaml
